# -*- coding: utf-8 -*-
"""AI ML Task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14L3eqOab4drrXQJ71H-oPFvDUz6qcGf_

#Loading The Important dependencies and model Yolo V8
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics
import ultralytics
ultralytics.checks()

from ultralytics import YOLO

from IPython.display import display, Image

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#Loading The Directory of Drive Where We Have stored our Train test and valid Data
# %cd /content/drive/MyDrive/Class/Yolo_V8

"""#Loading the Yolov8 Model And Training the Data on Our Data Set"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/Class/Yolo_V8
!yolo task=detect mode=train model=yolov8s.pt data= data.yaml epochs=25 imgsz=224 plots=True

!ls runs/detect/train/

#Model Evaluation Graph
Image(filename='runs/detect/train/results.png', width=600)

#Model Confusion Matrix
Image(filename='runs/detect/train/confusion_matrix.png', width=600)

"""# Validating The Model

"""

!yolo task=detect mode=val model=runs/detect/train/weights/best.pt data=data.yaml

Image(filename='runs/detect/train/val_batch0_pred.jpg', width=600)

"""#Predicting The Object Material Using Trained Model"""

!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt conf=0.25 source=data/test/images

#Displaying The Test DataSet Output
import os
from IPython.display import display, Image


folder_path = "/content/drive/MyDrive/Class/Yolo_V8/runs/detect/predict"

# Get the list of files in the folder
image_files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

# Display each image in the folder
for image_file in image_files:
    image_path = os.path.join(folder_path, image_file)
    display(Image(filename=image_path))

# To Predict The Matrial Object object just upload the file to collab and run the below code just give  the source of the image
#!yolo task=detect mode=predict model=runs/detect/train/weights/best.pt conf=0.25 source=<image source here>